### ISSUE TITLE
How can we attach the screenshot taken during the test cases execution and attached it as part of test log instead of just showing the output path?

### ISSUE THREAD

**Issue by csvipin31** [ObjectivityLtd/Ocaramba#102]
How can we attach the screenshot taken during the test cases execution and attached it to the test cases as part of test log, instead of just showing the output path of screen shot?

![image](https://user-images.githubusercontent.com/39784198/56261243-9dbf0c00-611d-11e9-9c66-39a186e7b93d.png)

Let me know 
if we could do it or not using this framework

**Comment by csvipin31** [comment]
Is there a way that i could hide log related to taking screenshot.
It's little bit unnecessary.
If there is any screen-shot, just attach it to test case.

**Comment by raczeja** [comment]
this functionality is related to Unit framework, it's supported by [NUnit ](https://github.com/ObjectivityLtd/Ocaramba/blob/master/Ocaramba.Tests.NUnit/ProjectTestBase.cs#L127)and [MsTest](https://github.com/ObjectivityLtd/Ocaramba/blob/master/Ocaramba.Tests.MsTest/ProjectTestBase.cs#L117), 

regarding the logging you can play with NLog setting in app.config
https://github.com/ObjectivityLtd/Ocaramba/wiki/Logging

**Comment by csvipin31** [comment]
thanks for the reply !!!
