### ISSUE TITLE
Css Selector : Issue

### ISSUE THREAD

**Issue by csvipin31** [ObjectivityLtd/Ocaramba#104]
CSSSelector : "[class='dropdown-menu inner']ul>li:visible"

I am using above mentioned selector in chrome colsole and it return me list of elements.

![image](https://user-images.githubusercontent.com/39784198/56555148-529e7080-65d7-11e9-93b2-33329ecbff5e.png)

When i use the same selector in the framework, i am getting Invalid selector.
![image](https://user-images.githubusercontent.com/39784198/56555126-3bf81980-65d7-11e9-919d-0d71d80786df.png)

Could you Please suggest if I am doing Anything wrong here.

**Comment by raczeja** [comment]
maybe that element is inside the iframe ? https://www.guru99.com/handling-iframes-selenium.html
