### ISSUE TITLE
Noob Questions/Issues Possibly...

### ISSUE THREAD

**Issue by Saieph** [ObjectivityLtd/Ocaramba#106]
Hey there! I'm embarking on using Ocaramba as a part of a larger framework test module project. We use MSTest as our unit framework, and I'm wondering EXACTLY what I would need to add to my package dependency for the project in order to reap the benefits of ALL of Ocaramba.

Presently, I have added the Ocaramba.MSTest nuget package to my manager, however the **NLog** references are not being honored, even though it appears that the package has downloaded.

Do I have to explicitly include all of the _source code_ from Ocaramba in my framework project, or is it all included as part of the Ocaramba.MSTest nuget?

Thank you!

**Comment by Saieph** [comment]
Additionally, in the ProjectTestBase.cs class, I cannot figure out for the life of me why the following is not being recognized:

`public TestContext TestContext { get; set; }`

**Comment by raczeja** [comment]
Ocaramba.MsTest should install all necessary dependences.
You can check https://github.com/ObjectivityLtd/Ocaramba.ProjectExample.MSTest project, and compare it with your solution.

**Comment by Saieph** [comment]
Thank you. Everything is working like a charm now. As a side question, is there any way to prevent/block the re-addition of the App.config, .runsettings and .testsettings files when restoring or re-importing the Ocaramba.MSTest nuget? Everytime I've added something to my package manager and installed, my App.config file gets overwritten. Thanks!

**Comment by raczeja** [comment]
I'm always ask by VS before overwriting those files, anyway we are planning to add Ocaramba package without app.config, ... , files and publish visual studio templates.
