### ISSUE TITLE
Support for .NET Standard / .NET Core / SpecFlow 3.x?

### ISSUE THREAD

**Issue by vamsitp** [ObjectivityLtd/Ocaramba#107]
Any tentative timelines for the same?

**Comment by matneyx** [comment]
I was wondering about SpecFlow 3 as well...

**Comment by matneyx** [comment]
I was wondering about SpecFlow 3 as well...

**Comment by raczeja** [comment]
we are planning  migration for .NET Standard / .NET Core, but I cannot give you any timelines, 
I hope it will be earlier than later

**Comment by matneyx** [comment]
Is it possible to get SpecFlow 3 support before .NET Standard / .NET Core?

**Comment by alan-Khadir** [comment]
When do you think the migration for .NET Standard / .NET Core be completed?

**Comment by raczeja** [comment]
unfortunately I'm not able to give you any exac date, but you can try the pre-release version https://www.nuget.org/packages/Ocaramba/3.2.1-alpha
