### ISSUE TITLE
Add an Example for DriverContext.CrossBrowserEnvironment Property

### ISSUE THREAD

**Issue by ghost** [ObjectivityLtd/Ocaramba#109]
Please add an example for DriverContext.CrossBrowserEnvironment Property.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://objectivityltd.github.io/Ocaramba/html/269c9e20-25d7-ec0d-f9cd-26b9dfce3de4.htm

**Comment by raczeja** [comment]
here you can find an example  https://github.com/ObjectivityLtd/Ocaramba/blob/master/Ocaramba.Tests.CloudProviderCrossBrowser/ProjectTestBase.cs#L51
