### ISSUE TITLE
Parallel Execution SpecFlow using Zalenium

### ISSUE THREAD

**Issue by alan-Khadir** [ObjectivityLtd/Ocaramba#110]
Hi, 

Very well written framework, thank you for all your efforts.

I'm using SpecFlow with NUnit and trying to run tests in parallel using Zalenium however I'm getting an error when running tests. 

I have set the below properties in App.config file.

` <add key="browser" value="RemoteWebDriver" />`
`<add key="DriverCapabilities" value="Chrome" />`
`<add key="RemoteWebDriverHub" value="http://localhost:4444/wd/hub" />`

Below is the error I'm getting.
![image](https://user-images.githubusercontent.com/51816882/60517658-f55e2400-9cd7-11e9-8403-a094fd80bc8a.png)

Does anyone here know what this error is and how it can be resolved?

Thank you,

**Comment by LouisVelez** [comment]
Where are you setting the `"name": create a quote with manual prices"` ?

**Comment by alan-Khadir** [comment]
I was setting the name (this.DriverContext.TestTitle = this.scenarioContext.ScenarioInfo.Title;) in the Before attribute. 
Removing this has now sorted out the issue I was having.
Thanks
