### ISSUE TITLE
Cannot run Chrome in Browserstack

### ISSUE THREAD

**Issue by denis-platonov** [ObjectivityLtd/Ocaramba#113]
Configured App.config as described in [docs](https://github.com/ObjectivityLtd/Ocaramba/wiki/Selenium-Grid-support):
`<add key="browser" value="RemoteWebDriver" />
    <add key="DriverCapabilities" value="Chrome" />
    <add key="RemoteWebDriverHub" value="http://user:key@hub-cloud.browserstack.com/wd/hub" />
`

Getting:
> Message: OpenQA.Selenium.WebDriverException : The property '#/' contains additional properties ["name"] outside of the schema when none are allowed in chromeOptions

Please, suggest a solution

**Comment by raczeja** [comment]
please try this configuration https://github.com/ObjectivityLtd/Ocaramba/wiki/Cross-browser-parallel-test-execution-with-SeleniumGrid-or-testing-Cloud-Providers

**Comment by denis-platonov** [comment]
Figured, that if I change value of DriverCapabilities to 'Firefox' but provide the rest of capabilities from Browserstack Capabilities Generator (including name of the browser there to Chrome) - it works )
