### ISSUE TITLE
Not all files created when installing NuGet package

### ISSUE THREAD

**Issue by jude-o** [ObjectivityLtd/Ocaramba#117]
- Ocaramba 3.16 and 3.15
- VS 2015/2019

I have created several new projects (.Net Framework class library, targeting 4.5) and installed Ocaramba through package manager console and through the Manage NuGet Packages context menu.

I assume the intended behavior is for the nuget packages to also create the app.config, ProjectTestBase, and ProjectPageBase classes, however, those files are not created. I've attached the output of the install below.

`Attempting to gather dependency information for package 'Ocaramba.3.1.15' with respect to project 'Mobile.Automation', targeting '.NETFramework,Version=v4.5'
Gathering dependency information took 4.61 sec
Attempting to resolve dependencies for package 'Ocaramba.3.1.15' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Ocaramba.3.1.15'
Resolved actions to install package 'Ocaramba.3.1.15'
Adding package 'Microsoft.AnalysisServices.AdomdClient.12.0.2000.8' to folder 'C:\Users\judeo\source\repos\Mobile.Automation\packages'
Added package 'Microsoft.AnalysisServices.AdomdClient.12.0.2000.8' to folder 'C:\Users\judeo\source\repos\Mobile.Automation\packages'
Added package 'Microsoft.AnalysisServices.AdomdClient.12.0.2000.8' to 'packages.config'
Successfully installed 'Microsoft.AnalysisServices.AdomdClient 12.0.2000.8' to Mobile.Automation
Adding package 'NLog.4.5.10' to folder 'C:\Users\judeo\source\repos\Mobile.Automation\packages'
Added package 'NLog.4.5.10' to folder 'C:\Users\judeo\source\repos\Mobile.Automation\packages'
Added package 'NLog.4.5.10' to 'packages.config'
Successfully installed 'NLog 4.5.10' to Mobile.Automation
Adding package 'NLog.Schema.4.5.10' to folder 'C:\Users\judeo\source\repos\Mobile.Automation\packages'
Added package 'NLog.Schema.4.5.10' to folder 'C:\Users\judeo\source\repos\Mobile.Automation\packages'
Added package 'NLog.Schema.4.5.10' to 'packages.config'
Successfully installed 'NLog.Schema 4.5.10' to Mobile.Automation
Adding package 'Selenium.WebDriver.3.141.0' to folder 'C:\Users\judeo\source\repos\Mobile.Automation\packages'
Added package 'Selenium.WebDriver.3.141.0' to folder 'C:\Users\judeo\source\repos\Mobile.Automation\packages'
Added package 'Selenium.WebDriver.3.141.0' to 'packages.config'
Successfully installed 'Selenium.WebDriver 3.141.0' to Mobile.Automation
Adding package 'Selenium.Support.3.141.0' to folder 'C:\Users\judeo\source\repos\Mobile.Automation\packages'
Added package 'Selenium.Support.3.141.0' to folder 'C:\Users\judeo\source\repos\Mobile.Automation\packages'
Added package 'Selenium.Support.3.141.0' to 'packages.config'
Successfully installed 'Selenium.Support 3.141.0' to Mobile.Automation
Adding package 'Selenium.WebDriver.ChromeDriver.73.0.3683.68' to folder 'C:\Users\judeo\source\repos\Mobile.Automation\packages'
Added package 'Selenium.WebDriver.ChromeDriver.73.0.3683.68' to folder 'C:\Users\judeo\source\repos\Mobile.Automation\packages'
Added package 'Selenium.WebDriver.ChromeDriver.73.0.3683.68' to 'packages.config'
Successfully installed 'Selenium.WebDriver.ChromeDriver 73.0.3683.68' to Mobile.Automation
Adding package 'Selenium.WebDriver.GeckoDriver.Win64.0.24.0' to folder 'C:\Users\judeo\source\repos\Mobile.Automation\packages'
Added package 'Selenium.WebDriver.GeckoDriver.Win64.0.24.0' to folder 'C:\Users\judeo\source\repos\Mobile.Automation\packages'
Added package 'Selenium.WebDriver.GeckoDriver.Win64.0.24.0' to 'packages.config'
Successfully installed 'Selenium.WebDriver.GeckoDriver.Win64 0.24.0' to Mobile.Automation
Adding package 'Selenium.WebDriver.IEDriver.3.141.59' to folder 'C:\Users\judeo\source\repos\Mobile.Automation\packages'
Added package 'Selenium.WebDriver.IEDriver.3.141.59' to folder 'C:\Users\judeo\source\repos\Mobile.Automation\packages'
Added package 'Selenium.WebDriver.IEDriver.3.141.59' to 'packages.config'
Successfully installed 'Selenium.WebDriver.IEDriver 3.141.59' to Mobile.Automation
Adding package 'Ocaramba.3.1.15' to folder 'C:\Users\judeo\source\repos\Mobile.Automation\packages'
Added package 'Ocaramba.3.1.15' to folder 'C:\Users\judeo\source\repos\Mobile.Automation\packages'
Added package 'Ocaramba.3.1.15' to 'packages.config'
Successfully installed 'Ocaramba 3.1.15' to Mobile.Automation
Executing nuget actions took 3.82 sec
Time Elapsed: 00:00:08.7508910
========== Finished ==========`

![Mobile Automation - Microsoft Visual Studio - 2019-09-16 11_49_12](https://user-images.githubusercontent.com/5510487/64980905-1d413a80-d878-11e9-8591-e8026d38e152.png)

---EDIT---

I can see in the nuspec that the file creation was done in the NUnit (for example) packages, but those are now marked deprecated. How should a new project be structured and where does that come from?

**Comment by raczeja** [comment]
Ocaramba nuget package doesn't contain those additional files. you can use Visual Studio template instead https://github.com/ObjectivityLtd/Ocaramba.templates
