### ISSUE TITLE
AngularPageNavigationTest  - may be failing on chrome 77+

### ISSUE THREAD

**Issue by mwyrodek** [ObjectivityLtd/Ocaramba#118]
Looks like there is some change in new chrome that makes problem with this test

code is failing oin 
```c#
                var perfLogs = logs.GetLog("performance");
``` 
looks like there was some change in new chrome or its driver - needs further investigation

**Comment by raczeja** [comment]
Issue related to two defects in Selenium
https://github.com/SeleniumHQ/selenium/issues/7900
https://github.com/SeleniumHQ/selenium/issues/7335
