### ISSUE TITLE
Tests in Test Explorer are grayed out and not running after updating test project to .Net Core 2.2

### ISSUE THREAD

**Issue by alan-Khadir** [ObjectivityLtd/Ocaramba#120]
Hi, 

I have updated my Test project to .Net Core 2.2 however when I try to run the tests in Test Explorer the tests are grayed out and not running. 

I have uninstalled, reinstalled and updated all NuGet packages including TestAdapter and Selenium browser drivers. Also the project builds fine without any errors and have relaunched visual studio several times.

My test project uses NUnit 3, Speflow 3 and .Net Core 2.2

Please note the tests run fine when targeting net472.

I know the problem is with my test project and not your framework but just wondering if anyone has had this problem or know what it might be.

Thanks for your help,

Alan

**Comment by JHBonarius** [comment]
What was the solution? I also have this problem...

**Comment by raczeja** [comment]
please use it with netcoreapp3.1, and SpecFlow 3.6.23, it is working for me
![image](https://user-images.githubusercontent.com/12324498/121892834-8855c480-cd1d-11eb-8d90-081f3adaff13.png)
