### ISSUE TITLE
How can we Re-run Failed specflow test cases from tear down??

### ISSUE THREAD

**Issue by csvipin31** [ObjectivityLtd/Ocaramba#122]

**Comment by mwyrodek** [comment]
Hi  Vipin.
Thanks for using our tool!

Could you tell me a little more what are you trying to achieve?
Usually, you shouldn't rerun test from the teardown - that should be handled by a separate mechanism, for example on the level of ci pipeline.

But, there is a plugin for specflow that allows this :  https://www.nuget.org/packages/specflow.retry
But I haven't used it so I can't guarantee it will work with Ocaramba.

There are other ways you can try:
https://stackoverflow.com/a/31402364
https://stackoverflow.com/questions/31380000/webdriver-use-afterscenario-to-rerun-failed-test-before-report-is-generated

**Comment by csvipin31** [comment]
I have some flaky UI test, which sometime fails and some time passes. so I am thinking of putting some logic to check if the test scenario fails, i would re-run these test cases once more.

I Azure build pipeline we could do re-run the test cases based on mim Faliure Count or %.
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/vstest?view=azure-devops
"rerunFailedTests
"
I could find anything silimar in teamcity.

So I thought if I could check the status of test in [Afterscenario] and re-run it.

**Comment by mwyrodek** [comment]
I see, Unfortunately, As I stated above this shouldn't be resolved on the level of Ocaramba code.

I had asked around, and the most common solution is to write a custom script for TeamCity to enable test reruns.

If you would like to pursue the path of doing it inside your solution you could try the plugin I mentioned ( https://www.nuget.org/packages/specflow.retry)

Or build something similar to the idea from this article: https://teamcity-support.jetbrains.com/hc/en-us/community/posts/206869065-Can-you-make-TeamCity-automatically-re-run-individual-tests-when-they-have-failed

or 
https://github.com/atinfo/at.info-knowledge-base/tree/master/programming/java/junit/run_failed_tests


Unfortunately, Ocaramba out of the box doesn't provide this functionality, we believe it should be handled on CI level.
