### ISSUE TITLE
Support for PhantomJS

### ISSUE THREAD

**Issue by artkpv** [ObjectivityLtd/Ocaramba#74]
Hi, thanks for this lib!
How to make it to use PhantomJs? No such driver listed at `Test.Automation/Objectivity.Test.Automation.Common/BrowserType.cs` and it throws `System.NotSupportedException : Driver None is not supported` when `<add key="browser" value="PhantomJs" />`

**Comment by raczeja** [comment]
Hi,
Selenium support for [PhantomJS ](https://github.com/ariya/phantomjs/issues/15344) has been [deprecated](https://github.com/SeleniumHQ/selenium/commit/c5e4a585f1e3c4b3468ec93ab50d3668d47aef1b#diff-16fa7e439f764ef9668676a211769d37R8), please use headless versions of [Chrome ](https://medium.com/@pyzzled/running-headless-chrome-with-selenium-in-python-3f42d1f5ff1d)or Firefox instead or you can use version 3.1.1 of our framework

to set chrome arguments use following section in app.config
  <ChromeArguments>
    
</ChromeArguments>
