### ISSUE TITLE
Add an Example for WebElementExtensions.SetAttribute Method

### ISSUE THREAD

**Issue by OlafStolle** [ObjectivityLtd/Ocaramba#97]

**Comment by raczeja** [comment]
that method contains example, and also is used in test https://github.com/ObjectivityLtd/Ocaramba/blob/bf0664683d7b5c54c9eb50ceb4dc79422ab0c302/Ocaramba.Tests.PageObjects/PageObjects/TheInternet/InternetPage.cs#L219
